/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author Raifuru
 */
public class PilihGambarButtonFullScreen extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButton
     */
    public PilihGambarButtonFullScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        btnGambar1 = new javax.swing.JButton();
        btnGambar2 = new javax.swing.JButton();
        btnGambar3 = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        imagePanel = new javax.swing.JPanel();
        lblGambar1 = new javax.swing.JLabel();
        lblGambar2 = new javax.swing.JLabel();
        lblGambar3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGambar1.setText("Gambar 1");
        btnGambar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGambar1ActionPerformed(evt);
            }
        });
        buttonPanel.add(btnGambar1);

        btnGambar2.setText("Gambar 2");
        btnGambar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGambar2ActionPerformed(evt);
            }
        });
        buttonPanel.add(btnGambar2);

        btnGambar3.setText("Gambar 3");
        btnGambar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGambar3ActionPerformed(evt);
            }
        });
        buttonPanel.add(btnGambar3);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        buttonPanel.add(btnExit);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        imagePanel.setLayout(new java.awt.CardLayout());

        lblGambar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGambar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/gambar1.jpg"))); // NOI18N
        imagePanel.add(lblGambar1, "0");

        lblGambar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGambar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/gambar2.jpg"))); // NOI18N
        imagePanel.add(lblGambar2, "1");

        lblGambar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGambar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/gambar3.png"))); // NOI18N
        imagePanel.add(lblGambar3, "2");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGambar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGambar1ActionPerformed
          CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel, "0");
    }//GEN-LAST:event_btnGambar1ActionPerformed

    private void btnGambar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGambar2ActionPerformed
         CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel, "1");
    }//GEN-LAST:event_btnGambar2ActionPerformed

    private void btnGambar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGambar3ActionPerformed
          CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel, "2");
    }//GEN-LAST:event_btnGambar3ActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               PilihGambarButtonFullScreen fullFrame = new PilihGambarButtonFullScreen();
                
                GraphicsDevice device =
                        GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
                device.setFullScreenWindow(fullFrame);
                        
                
                fullFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGambar1;
    private javax.swing.JButton btnGambar2;
    private javax.swing.JButton btnGambar3;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel lblGambar1;
    private javax.swing.JLabel lblGambar2;
    private javax.swing.JLabel lblGambar3;
    // End of variables declaration//GEN-END:variables
}
